### ISSUE TITLE
loadImage with cors in v3

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-io#2]
how to pass `corssOrigin = "Anonymous"` in the new api that's using fetch underneath? Also isn't falling back to blob and createObjectURL slowing things down the moment options are provided?

Here is function i'm trying to achieve

```js
function loadImage(url) {
    return new Promise((resolve, reject) => {
      const downloadedImg = new Image();
      downloadedImg.crossOrigin = "Anonymous";
      downloadedImg.addEventListener("load", () => {
        resolve(downloadedImg);
      });
      downloadedImg.addEventListener("error", reject, false);
      downloadedImg.src = url;
    });
  }
```

**Comment by dmnsgn** [comment]
So currently in v3, every loadFn function is accepting the [options object for fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch) as the second argument:

So one of these might work:
```js
await loadImage(urlOrOpts, { mode: "cors" }) // or no-cors or same-origin
// or to set the property on the image
await loadImage({ url, crossOrigin: "anonymous" })
// or a combination of both
```

I have benchmarked and it is indeed faster to not use a blob and pass url directly to src. Now the question is one of consistency and API:
```js
// 1. Only url as first and opts as second, no blob url
await loadImage(url, imageOpts)

// 2. url or opts as first argument only
await loadImage(urlOrOpts)

// 3. use fetch as blob only if options are passed
await loadImage(urlOrOpts, fetchOptions)

// 4. add more parsing options eg. no-parse/"blob"/"base64"
await loadImage(urlOrOpts, parse?)
```

**Comment by vorg** [comment]
Actually turns out that i was stuck at v2 and after upgrading to v3 i don't have problems with cors tinting. Closing for now until i run into same problem again.
